### ISSUE TITLE
Integration test for DB upgrades

### ISSUE THREAD

**Issue by dvdplm** [paritytech/polkadot#5172]
In the light of https://github.com/paritytech/polkadot/issues/5168 it would be good to have zombienet tests in place to test DB version upgrades for both rocksdb and paritydb.

**Comment by cheme** [comment]
cc @pepoviola

**Comment by pepoviola** [comment]
Hi @cheme, we can use this config to test a network of two validators, with one validator using `paritydb`.

```toml
[settings]
timeout = 1000
bootnode = false

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  args = [ "-lparachain=debug", "--database=paritydb-experimental" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "-lparachain=debug" ]


[[parachains]]
id = 100
addToGenesis = false

  [[parachains.collator_groups]]
    count = 1
    [parachains.collator_groups.collator]
    name = "collator"
    command = "adder-collator"
    image = "{{COL_IMAGE}}"
```

And we can test that both nodes are `up` and other metric that you need.

Thanks!
